networks:
  node:
    internal: true
  nginx:

services:
  node:
    build:
      context: ${PWD}/node
    user: nonroot
    read_only: true
    networks:
      node:
        aliases:
          - node.lokal
    cap_drop:
      - ALL

  nginx:
    image: nginx:alpine
    user: nginx
    read_only: true
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    tmpfs:
      - /tmp
      - /var/cache/nginx:uid=101,gid=101,mode=700
      - /var/run:uid=101,gid=101,mode=700
    cap_drop:
      - ALL
    networks:
      node:
        aliases:
          - stripe.lokal
          - github.lokal
      nginx:
    ports:
      - 3000:3000
